ASide:
  - Room: "start"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 23
        Y: 224
  - Room: "s0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Dashes: zero
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "s1"  # TODO one day we will be able to categorize this room correctly
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 96
        Y: 40
    #InternalEdges:
    #- Split: TopToBottom
    #  ReqOut:
    #    Dashes: zero
    #  ReqIn:
    #    Dashes: one
  - Room: "s2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    End: true
  - Room: "0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 32
      Name: "lightbeam"
      Update:
        Remove: true
  - Room: "1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 160
      Y: 280
      Update:
        Default: true
    - ID: 50
      Name: "lightbeam"
      Update:
        Remove: true
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
  - Room: "2"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    Subrooms:
    - Room: "peek"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 376
      Y: 448
      Update:
        Default: true
    - Name: "darkChaserEnd"
      Update:
        Add: true
        X: 136
        Y: 224
        Width: 24
        Height: 128
    - Name: "darkChaserEnd"
      Update:
        Add: true
        X: 0
        Y: 352
        Width: 160
        Height: 24
    - ID: 3
      Name: "invisibleBarrier"
      Update:
        Remove: true
  - Room: "3x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "3"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "4"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
    - Collectable: 0
      ReqBoth:
        Dashes: one
    Tweaks:
    - Name: "spawn"
      X: 296
      Y: 168
      Update:
        X: 288
    - ID: 0
      Name: "jumpThru"
      Update:
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 24
        Y: 48
  - Room: "5"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "6"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "7"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "8"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
    InternalEdges:
    - To: "exit"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - ID: 32
      Name: "jumpThru"
      Update:
        Width: 32
    - ID: 0
      Name: "jumpThru"
      Update:
        Width: 16
    - Name: "spawn"
      X: 368
      Y: 304
      Update:
        X: 360
    - Name: "spawn"
      Update:
        Add: true
        X: 384
        Y: 96
  - Room: "9"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "acrossTheDreamBlock"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "acrossTheDreamBlock"
      Holes:
      - Side: Up
        Idx: 1
        Kind: inout
        ReqOut:
          Dashes: one
      - Side: Down
        Idx: 1
        Kind: out
        ReqOut:
          Or:
          - Dashes: one
          - Dashes: zero
            Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 200
        Y: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 472
        Y: 264
    - ID: 33
      Update:
        Remove: true
    - ID: 34
      Name: "invisibleBarrier"
      Update:
        Remove: true
    - ID: 38
      Name: "lightbeam"
      Update:
        Remove: true
  - Room: "9b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
    - Side: Down
      Idx: 3
      Kind: none
    Tweaks:
    - ID: 0
      Name: "jumpThru"
      Update:
        Width: 16
    - Name: "spawn"
      X: 424
      Y: 312
      Update:
        X: 416
    - Name: "spawn"
      Update:
        Add: true
        X: 248
        Y: 272
  - Room: "10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    Tweaks:
    - ID: 97
      Name: "lightbeam"
      Update:
        Remove: true
    - Name: "spawn"
      Update:
        Add: true
        X: 128
        Y: 944
    - ID: 87
      Name: "invisibleBarrier"
      Update:
        Remove: true
  - Room: "11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12b"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "12c"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12d"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "13"
    Holes:
    - Side: Left
      Idx: 0
      Kind: None
    # TODO: Warp
  - Room: "d0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - To: "lower"
      ReqOut:
        Dashes: zero
    - To: "middle_right"
      ReqBoth:
        Dashes: one
    - Collectable: 0
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "lower"
      Holes:
      - Side: Down
        Idx: 0
        Kind: inout
        ReqBoth:
          Dashes: one
      - Side: Left
        Idx: 2
        Kind: inout
      - Side: Right
        Idx: 2
        Kind: inout
        ReqOut:
          Dashes: one
      InternalEdges:
      - To: "middle_right"
        ReqOut:
          Dashes: one
        ReqIn:
          Dashes: zero
    - Room: "middle_right"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
  - Room: "d1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
  - Room: "d2"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "berry1"
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "berry1"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      Collectables:
      - Idx: 0
    Tweaks:
    - ID: 30
      Name: "exitBlock"
      Update:
        Remove: true
    - ID: 29
      Name: "invisibleBarrier"
      Update:
        Remove: true
  - Room: "d3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - Split: TopToBottom
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 2
        Kind: inout
  - Room: "d4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "d5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d6"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqIn:
        Dashes: one
        Difficulty: hard
  - Room: "d7"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "d8"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "right"
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 1
        Kind: inout
    Tweaks:
    - ID: 16
      Name: "jumpThru"
      Update:
        X: 280
        Width: 24
  - Room: "d9"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "end_0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in 
    - Side: Up
      Idx: 1
      Kind: in #the two ins are accessible from each other technically
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 264
        Y: 56
    - Name: "spawn"
      Update:
        Add: true
        X: 32
        Y: 320
    - ID: 0
      Name: "goldenBerryCollectTrigger"
      Update:
        Remove: true
  - Room: "end_1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 80
        Y: 104
    - Name: "spawn"
      Update:
        Add: true
        X: 352
        Y: 88
  - Room: "end_2"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: inout
    Subrooms:
    - Room: "theo"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      - Side: Left
        Idx: 1
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 8
        Y: 88
  - Room: "end_3"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "end_3b"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_3c"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "end_3cb"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
  - Room: "end_4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_5"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_6"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 304
        Y: 152
  - Room: "end_s0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "end_s1"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout

BSide:
  - Room: "start"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 32
        Y: 160
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 264
        Y: 16
  - Room: "01b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
    Tweaks:
    - ID: 0
      Update:
        Width: 16
    - Name: "spawn"
      Update:
        Add: true
        X: 456
        Y: 32
  - Room: "02b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
    Tweaks:
    - Name: "dreamBlock"
      ID: 7
      Update:
        Y: 16
        Height: 88
    - Name: "spawn"
      Update:
        Add: true
        X: 606
        Y: 16
    - ID: 0
      Name: "jumpThru"
      Update:
        X: 24
        Width: 24
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 576
        Y: 8
        Width: 48
        Height: 16
        Values:
          cameraX: -1
          cameraY: 0
  - Room: "02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
    Tweaks:
    - ID: 0
      Update:
        X: 24
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 880
        Y: 24
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 848
        Y: 8
        Width: 48
        Height: 16
        Values:
          cameraX: -1
          cameraY: 0
  - Room: "03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
  - Room: "04"  # TODO when we can edit fg tiles, remove the leftmost spikes and blocks under it
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 40
        Y: 24
  - Room: "05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
    Tweaks:
    - ID: 0
      Update:
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 296
        Y: 24
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 1
      Name: "invisibleBarrier"
      Update:
        Remove: true
  - Room: "08b"
    Holes:
    - Side: Up
      Idx: 2
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - ID: 12
      Update:
        Y: 16
        Height: 104
  - Room: "08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "end"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 248
        Y: 448
    End: true

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 10
      Name: "exitBlock"
      Update:
        Remove: true
    - ID: 9
      Name: "invisibleBarrier"
      Update:
        Remove: true
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
        Difficulty: hard
    End: true
