CollectableNames:
  - "strawberry"
  - "key"
  - "summitgem"
Music:
  - Name: "event:/music/lvl0/intro"
  - Name: "event:/music/lvl1/main"
    Weight: 3  # ;)
  - Name: "event:/music/lvl1/theo"
  - Name: "event:/music/lvl2/beginning"
  - Name: "event:/music/lvl2/mirror"
    Weight: 2
  - Name: "event:/music/lvl2/evil_madeline"
  - Name: "event:/music/lvl2/chase"
  - Name: "event:/music/lvl2/awake"
  - Name: "event:/music/lvl3/intro"
  - Name: "event:/music/lvl3/explore"
    Weight: 2
  - Name: "event:/music/lvl3/clean"
    Weight: 2
  - Name: "event:/music/lvl3/oshiro_theme"
  - Name: "event:/music/lvl3/oshiro_chase"
  - Name: "event:/music/lvl4/main"
    Weight: 2
  - Name: "event:/music/lvl4/heavy_winds"
  - Name: "event:/music/lvl4/minigame"
  - Name: "event:/music/lvl5/normal"
  - Name: "event:/music/lvl5/middle_temple"
  - Name: "event:/music/lvl5/mirror"
  - Name: "event:/music/lvl6/madeline_and_theo"
  - Name: "event:/music/lvl6/starjump"
    Weight: 0.5
  - Name: "event:/music/lvl6/the_fall"
  - Name: "event:/music/lvl6/badeline_fight"
  - Name: "event:/music/lvl6/badeline_glitch"
  - Name: "event:/music/lvl6/badeline_acoustic"
  - Name: "event:/music/lvl6/main"
  - Name: "event:/music/lvl6/secret_room"
    Weight: 0.5
  - Name: "event:/music/lvl7/main"
  - Name: "event:/music/lvl7/final_ascent"
  - Name: "event:/music/lvl8/main"
  - Name: "event:/music/lvl9/main"
  - Name: "event:/new_content/music/lvl10/part01"
    Weight: 2
    Parameters:
      progress: 1
  - Name: "event:/new_content/music/lvl10/part02"
  - Name: "event:/new_content/music/lvl10/part03"
  - Name: "event:/new_content/music/lvl10/intermission_heartgroove"
  - Name: "event:/new_content/music/lvl10/reconciliation"
  - Name: "event:/new_content/music/lvl10/final_run"
  - Name: "event:/new_content/music/lvl10/cinematic/end"
  - Name: "event:/new_content/music/lvl10/granny_farewell"
    Weight: 0.5
  - Name: "event:/new_content/music/lvl10/golden_room"
    Weight: 0.5
  - Name: "event:/classic/pico8_mus_00"
    Weight: 0.5
  - Name: "event:/classic/pico8_mus_01"
  - Name: "event:/classic/pico8_mus_02"
  - Name: "event:/classic/pico8_mus_03"
  - Name: "event:/music/remix/01_forsaken_city"
  - Name: "event:/music/remix/02_old_site"
  - Name: "event:/music/remix/03_resort"
  - Name: "event:/music/remix/04_cliffside"
  - Name: "event:/music/remix/05_mirror_temple"
  - Name: "event:/music/remix/06_reflection"
  - Name: "event:/music/remix/07_summit"
  - Name: "event:/music/remix/09_core"
Backgrounds:
  - Texture: "bgs/07/bg0"
    Opaque: true
    LoopY: true
  - Texture: "bgs/06/plateau/bg0"
    Opaque: true
    LoopX: false
    ScrollFactorX: 0
    ScrollFactorY: 0
  - Texture: "bgs/06/bg0"
    Opaque: true
    LoopY: true
  - Texture: "bgs/10/sky"
    Opaque: true
    LoopY: true
  - Texture: "bgs/10/skybrighter"
    Opaque: true
    LoopY: true
  - Effect: "stars"
    Opaque: true
  - Effect: "northernlights"
    Opaque: true
  - Effect: "blackhole"
    Opaque: true
  - Texture: "bgs/07/00/bg1"
    CoverBottom: 18
  - Texture: "bgs/07/00/bg2"
    CoverBottom: 28
  - Texture: "bgs/07/01/bg1"
    CoverBottom: 50
  - Texture: "bgs/07/01/bg2"
    CoverBottom: 12
  - Texture: "bgs/07/01/bg3"
    CoverBottom: 33
  - Texture: "bgs/07/02/bg1"
    CoverBottom: 51
  - Texture: "bgs/07/02/bg2"
    CoverBottom: 45
  - Texture: "bgs/07/02/bg3"
    CoverBottom: 24
  - Texture: "bgs/06/bg1"
    LoopY: true
    NeedsColor: true
  - Texture: "bgs/06/bg2"
    LoopY: true
    NeedsColor: true
  - Texture: "bgs/05/temple/bg3"
    LoopY: true
    NeedsColor: true
  - Texture: "bgs/05/mirror/bg4"
    LoopY: true
BgEffects:
  - Effect: "snowBg"
  - Effect: "dreamstars"
  - Effect: "planets"
    AndThen:
      Effect: "planets"
      OffX: 20
      OffY: 7
      ScrollFactorX: 1.3
      ScrollFactorY: 1.2
  - Effect: "starfield"
    AndThen:
      Effect: "starfield"
      OffX: 20
      OffY: 7
      ScrollFactorX: 1.3
      ScrollFactorY: 1.2
  - Texture: "mist"
    LoopY: true
FgEffects:
  - Effect: "stardust"
    ProvidesWind: true
  - Effect: "windsnow"
    ProvidesWind: true
  - Effect: "rain"
  - Effect: "snowFg"
  - Effect: "mirrorFg"
  - Effect: "reflectionFg"
  - Effect: "petals"
  - Effect: "godrays"
  - Texture: "mist"
    LoopY: true
    SpeedX: 16
    SpeedY: 8
    Alpha: 0.6
    BlendMode: "additive"
    AndThen:
      Texture: "mist"
      LoopY: true
      SpeedX: 4
      SpeedY: 4
      ScrollFactorX: 0.5
      ScrollFactorY: 0.5
      Alpha: 0.6
      BlendMode: "additive"
  - Texture: "purplesunset"
    LoopY: true
    SpeedX: 4
    SpeedY: 4
    Alpha: 0.25
    BlendMode: "additive"
Rulesets:
  - Name: A
    LongName: "Default (A)"
    Algorithm: Pathway
    Darkness: Never
  - Name: B
    LongName: "2dash (B)"
    Algorithm: Pathway
    Dashes: Two
    Darkness: Never
  - Name: C
    LongName: "Expert (C)"
    Algorithm: Pathway
    Difficulty: Expert
    DificultyEagerness: High
  - Name: D
    LongName: "Expert 2dash (D)"
    Algorithm: Pathway
    Difficulty: Expert
    DificultyEagerness: High
    Dashes: Two
  - Name: E
    LongName: "Standard Labyrinth (E)"
    Algorithm: Labyrinth
    Length: Medium
    Darkness: Never
  - Name: F
    LongName: "Hard Labyrinth (F)"
    Algorithm: Labyrinth
    Length: Medium
    Dashes: Two
    Difficulty: Hard
    Darkness: Never
  - Name: G
    LongName: "Standard Endless (G)"
    Algorithm: Endless
    EndlessLives: 3
    Lights: On
    Strawberries: Low
    Lives: 3
  - Name: H
    LongName: "Hard Endless (H)"
    Algorithm: Endless
    EndlessLives: 5
    Difficulty: Hard
    Lights: On
    Strawberries: High
    Lives: 5
